### ISSUE TITLE
Installer for Fedora?

### ISSUE THREAD

**Issue by derekatkins** [einheit/maia_mailguard_1.04a#12]
It would be nice to have a Fedora installer script, too.  At least we should support F31 and F32 (F32 was just released a few days ago, April, 2020).  As discussed on the maia-users list, I am willing to help write this script if jjs doesn't.

**Comment by einheit** [comment]
The first cut at a F32 installer was almost a success, the only issue I  ran into was the wddx support. The wddx workaround that fixed it on ubuntu-20.04 didn't work for F32. 

![Screenshot at 2020-04-30 17-11-45](https://user-images.githubusercontent.com/5245842/80770685-bff7b200-8b05-11ea-87b5-9f4ad64b52ef.png)

**Comment by einheit** [comment]
F32 installer working here. We removed the dependency on php-wddx since it no longer seems to be needed.
