### ISSUE TITLE
Receive TROUBLE in check_mail: spam_scan FAILED: DBD::mysql::st execute failed: Incorrect string value: '\\xF0\\x9F\\x92\\xB8Th...' 

### ISSUE THREAD

**Issue by mjpcomp** [einheit/maia_mailguard_1.04a#14]
Ubuntu 20.04 + MariaDB (mariadb  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2) = from  Ubuntu repository using the installer script

Looks like there may be a collation/character set problem when receiving e-mails with subjects containing emoji or other characters? The default collation appears to be utf8, however, the old Maia MailGuard on CentOS from 10 years ago that's running is using latin1_swedish_ci, and doesn't have this problem.

Unsure on if this is a problem only I've encountered, or, may be something that needs to be adjusted in the SQL script?

![image](https://user-images.githubusercontent.com/7637082/91111248-e30a1c80-e634-11ea-903b-51328adfa44f.png)

**Comment by mjpcomp** [comment]
Had to convert the maia DB from utf8 to utf8mb4 (followed this https://logic.edchen.org/how-to-convert-an-entire-database-from-utf8-to-utf8mb4/ to do the conversion)... Emoji is now coming through subjects

**Comment by einheit** [comment]
Thank you for this. It was a corner case I hadn't seen until now.
